version: 0.0
os: linux
files:
  - source: /
    destination: /usr/share/nginx/html/CodeDeployGitHubDemo
hooks:
  AfterInstall:
    - location: script/change_permissions.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: script/start_server.sh
      timeout: 300
      runas: root
  ApplicationStop:
    - location: script/stop_server.sh
      timeout: 300
      runas: root
